### ISSUE TITLE
The PDF linked from the readme is not available.

### ISSUE THREAD

**Issue by chrisvest** [pramalhe/RedoDB#1]
The readme file has links to this PDF file, which is not available at that URL: https://github.com/pramalhe/RedoDB/blob/master/RedoDB-2020.pdf

Can the PDF file be uploaded, or the links changed to point to a location where the PDF file is available?

**Comment by taovcu** [comment]
Hi, do you want me email you the paper?

**Comment by chrisvest** [comment]
@taovcu I read the preprint already, and don't need the final copy. Others might want it, and there's still that dead link in the readme, so if you're allowed to upload the paper then that would be best, otherwise it might make sense to change the link to reference the preprint?

**Comment by carlopires** [comment]
Is the paper PDF available from some accessible place? I tried https://dl.acm.org/doi/abs/10.1145/3342195.3387515, but it is offered to purchase and I'm not sure if it is the same paper.

**Comment by pramalhe** [comment]
I've uploaded a version of the paper on the repo and yes, it's the same one.
Thank you for the interest! 
If you have further questions do let me know.
